### PR TITLE
Fixed `Export All` selector

### PR DESCRIPTION
**Pull request by br-g**
The export was not working anymore because of the new "Feedback" button in Roam Research.
This new selector fixes the problem.

### CODE REVIEW

**Comment by everruler12** [comment]
The export has been working for me since the fix from https://github.com/everruler12/roam2github/commit/2009fecb67d186d1bdf16eeec4a577af8bb5c9d8

**Comment by br-g** [comment]
Oh I just realized the "Feedback" button only appears in the "help" database (https://roamresearch.com/#/app/help).
So this should fix the export of the "help" database only.

**Comment by everruler12** [comment]
Yes, that's exactly what the https://github.com/everruler12/roam2github/commit/2009fecb67d186d1bdf16eeec4a577af8bb5c9d8 fix was for. I haven't had issues with exporting the Help graph since then. I'm wondering if maybe you had a fork that didn't get that update?

**Comment by br-g** [comment]
You're right, I wasn't properly updated. Sorry for that!

**Comment by everruler12** [comment]
No worries! I appreciate you willing to help out

**Pull request closed without merging**
